use_frameworks!

target 'CTLCubeContainerViewController_Example' do
  pod 'CTLCubeContainerViewController', :path => '../'

  target 'CTLCubeContainerViewController_Tests' do
    inherit! :search_paths

    
  end
end
